data:
  project_id: padl-demo
  variables:
    ANY_SECRET: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      MmExYzNmMjM1YjU3NWM0NTlhOGFkZWZhMDVhZTg5Y2EoS2oxVzFXRGVGVDgvZVlo
      dU9FOFpMUWUvdnlyRStYU0FzUUlJbWVpcXd2c1h5WjZIaHN2eGtxYXRvTzhMVyty
      emZ1NVlOaThEZFIxVWthaGNSa2RlQkp5RFUzV21vbVl3bDBEemdWbU5qRUNveWZ2
      ZGljQW01T1BBMkdxcml3QjlNcGtWZkN3VkdyV2t5REQ3dWpaRGpROWVhZ043NHRy
      SnE3NWFpcGp0b24wZUkzUjlBeVpxN0toSXBKVU1EMWNMZ05oZmNhSyswOTV3ajcv
      UzAxMkF0WEtTZVZNZXJwUnlHdm9TaGpoZ0NuOGVrK3N5UzBIbW9Mb2piQzExUTFi
      bW9GaFVtWTM0TFRucmQzNnZ2UzY4M1hEMFhkd3JpL3VnZU83NHI3anVuTmpFYzJF
      bzdpQWFBemc1VjJTOU95UkhxYXhudTNyemRFcG9oYS9zUG9uT3F3PT0pCjFlZGY0
      Yzc3ZmJhYjRjZDU2ZjdjMGZiNjRhNmJmNTA2KEQ0UEpnd0xWS0ZMMlhObk1SVFVa
      TVo2dkdFTUd2SU42eUFsemF5ZWlSTUlXMUZlQmZxWG4xUzFlNzZrR3J1am5zck91
      OEVvZXJGZGQ4eTREQmhpWktuZHVrNEpBTitaRDRpU2FEZ3A1c3FsaEcvYTk0d3Vh
      ZDZhRjJRMGxjc3pTVWh6Z2JKaitOVjUvV0N0K1czV2hEM3pVSXRnN0dQeStvU0Zs
      SGJFWGNZS1lhVlI1MDhIQ3JmZXhwdUlTSC9LbExOZ0E1aWFyckpwbkJDY2U0eThp
      bzdLT0Urb0RWY2xLQnJZL3hWN2QxK0JuT09vY0dRUlhQa0ZJY0tPZExoOGI4c1BL
      RjRBVVhUTmR4eCtrWThIOFhyR2dUNTZIeHFjaXpRWEk3aU5vMmJXUlRySXhBNzVN
      ankyRytPVWljYjkwSVRQeVAzZUViVEpqYkk4VG5hM3p0MnpKeUNFZUJNUHA1cFRr
      UmE4Yy9GREkyRjNqQ2hqWDc5VDR4YmtoTGswR0Q0U2x3Nm9MRkJobCsyS2RmM0dv
      d0JNNG5STUhOd0dRTzFFMG1FSjlCeXU5alhZTktjYVJPelorN0E0bkFOb0YzcHdB
      dlNtSVZPNVp5bWk2TVFZRVFMYjY0bkJqTXRHeHVoK0k3ZVhLM1huRTVZaWtmVXRm
      RVltUlJvUDdrVU5vbExjaFlKRVRxaEtJMmpMQ0hMZTF1K0VPeFFUQWxtQzcyM1cw
      UDVoL09wY0ZxMkxPa3diQ0lBa3A2YkRmbUZzVHNhZ2ZkRUR0bkxManlIV0IvNUdR
      bWNLK050MHVEUE9wL1Q5RjJGVzlqTmdMWVJZOXpveGM0ekI3UjRqWmNRQXdJWFlQ
      VUdET0dRdkJpTWtBQmJrOWdhU202Wmg2K3dSVnpSNHI0YjMyTk5rPSkKZWI4YTkz
      MjQ1NmQzOGRmNzg5OGRhZjRjOTU3M2Y4YTUodUJKb0dzUWJDUUJIR1VzUTFYeWt1
      TlVnOGRrSlVNMXlSRDBjMDExdEZVRVFpVThiTFNLNDQ1QkNlbk01Mk44LzZsZjN3
      YjBoK2I5RzM5R3lMWWkreEwydlZIZCtOYW4wT2pZMDZkUko0cWhaUmNUSFFrcWw0
      U296RDZpenI3YmxMMWN5Mkt5czBYUzlJQ1huVE9RVlN0cnZvcXRwVTV3dW5iYlVq
      Zis5Zzd4dE5sMHB4S3JYeHRlWE9mT2EvNGZ6Z3gxZW4zdS80NnBoMjJWMlpTZjFa
      dzYrTC81SmszNHNwdXJIQkxOUnRscFdLOXdYaG96WE9HVE1VOStQNk5nTDk4QVZp
      RzA1aTY1WFFlYzY3aS9LYU5ENEg3Qjd5aklwWTh4dWxyL3pXa09VdFRwYXEzUmlR
      VC9jaFZ1YVhmRkxRbGN5UEdSejJONkJOVWh6R0czdWdwS21GYlVVS2JjUTl4bnhT
      R0RHZGc5dVJOclFRdUZ4c0NPU09tbVlqMFBsK2RiSXNKZlByWGpER3BodloxdFBi
      OTR1RTV0YXQ2OFowa1l5SG5DUU5sQ3JkNnEvYmFWdkV3QUsralZ0RldUZjNTengy
      eG5OVE5RakIxRHdMWWhvMngrY1ZNYXF4ejZ5TFRnSjlqM05VWUt4OWNXRXo5RHFv
      RDJOalZqcWtjMmpzcUlqTGZZNTYrb25RVHVwMUJDWFF5YWJZYUhXaW81K0grWEJR
      cTRWZkFoRGNLL29zK1F6QVRDMlJBV1dGbUppVWl0MHM4akJXTmxhUWVmcW0zWVpz
      RlArdkIrS1p1emkzU1MzdW8zeFQ5Z1o3d2dLZUVlRTFUeVBMYlVHSklNRVR5Rmdt
      TmROQjkwQ2JxWmdWSlR4QmFhWkQzL3oyUks4eVA3VUZpbHVYczA9KQ==
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 1edf4c77fbab4cd56f7c0fb64a6bf506
  - eb8a932456d38df7898daf4c9573f8a5
  service_keys: []
  shared_key: 2a1c3f235b575c459a8adefa05ae89ca
