data:
  project_id: demo-project
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      YmU4NDA1MThjM2Q0N2M0MGM0ZTAzOTlmZjBmNzM2MmUoNHVud3hhUE5PYm5XWWI2
      L3BXanRLc0RicllDd1I0ZjN0dkNtOXZCeU9iSjFNT2xiQ2h3eGdVYTRYei9tQ3Ix
      THhIbytzbTN0RWU5ekFEc2lxSUVDdjB3N29ZQlJndU5XRWVzT2Y4akFZRjBTOTBI
      OXBqWUY0LzhBV1MyN1NvZWkramV0eWtTbUJJa1FzamxYOWY0U3I5NkI1TEc2Vnhp
      U05rWk9nUG8wWnh2dFlMa1hSRW1HeU44V0t1WEJ0WDQrazNJSkxuZUlPa2xDalpO
      eTRrOVV6UGNqNWFTTkxQTlpHMUJwWmRMSWt0OXVVeGkweHFJNkpQSGM0V2YwVkZ2
      M2g3MlNJdFcwNWtRamlNamRTSzlsVWZHVkJnVUFwd1p6SU1aN3ExL2RGNjl4OU9F
      azZJeEhiZHlMd1FmbFU4MDFqQjJIMk9ZK3dYYytYUDN5YnRYOEF3PT0pCmNhMGNi
      ZjMyOTBkNzM4NmU3OGE0ZmI3NDBmYjE1MDZiKFFzNzJpWFlVOFNZMmtPam5Ha0xo
      Qmc4T3hSN2phVmlMNHp3UGcvUTdWeGQvNWhXSnkzeG9lbWg4bEM3cGlockEweFIr
      NGhjNTVHRHdyMmpnTVVmcVo5Y0gyVFQ3U2hjR2xoMEZSdTNpdWErajdPYUYrZ3pE
      YVF4ZE41Zmt3aWU1eGxvUlZCTnVLRzBHaTRmTmR1Z2VyaFVVM2xHWi9PbFBhZjhp
      aEVrVXZQa1lFQVRUWWF0V21uVVp2TmhoZjRYMGowYzNkTjU1TXBHcVlKUThNdmZJ
      MTlOb2tIYWRvaEFJVkd3ZHBTdlRSRDV2OFFRUVFjdnVxUzZ0K2R1eTNQN2lqK21k
      MkQ4TnFMcUloazdmTy8rSEpnTWhzVmZNWVY1UDk5Uk9HZjNMNXBoVEd0emFIdDUw
      RzV3RkUwNUZZNVA0RTgzSFRzb09VZ3N3NjE5SFNzQ0ZXcEtVYXhNNGVUd1JzWFpM
      NlRQK1NCWWdJN2lwamgvdHI3azFKNDlaVFdRNUY4QUdab3dQcmxlcEkwRUY3OTRm
      RHo5SnEwdG5aNURTK1dYdldXVUtDU283ZGN3enpnOUVPMDV1MmcwRVZJVkZ1Z0d2
      Y3FjdURBQ3NuWjQ0WDdBU21RV3NrdmRNUysybHgrbGk5TEx6OWFjZkVHcHlJUHhw
      Zzh3dnYxVkhGczVycUdsV3ZUNFZ1VHNXUElPUFJDcWxBeUVjbjBVWlF3TVFjTFRR
      Yk5QU1lDcTYxQUlPeW9JM0twODR4dVA4bjFpZkprenIxREJtSjZIdWd1cUFpODFi
      QmJpbUpyMnBVQ2NKdEJ0b0ZXSzFzYVZmdDRJbTNQVTczMzJ3QkRUdmZZVURtSTgz
      WndKb0QxazZDVHdCb0pFZ0hYOGpKNE9Xd2hnemp2ZHdxWHhRYktZPSk=
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - ca0cbf3290d7386e78a4fb740fb1506b
  service_keys: []
  shared_key: be840518c3d47c40c4e0399ff0f7362e
