data:
  project_id: demo-project-2
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      Y2MyNGU0NTRlNGI4YTk1NGJmM2E5MDM3YWYzMDU4ZmIoSW9GQitkeE9ZMnZ3MjRR
      ZmhLdG05NkVFTUhJYllVMUhBNHpWQzc1Nlk3Uyt6OUREK3pjK3JvdzA1MnpTQVhI
      V2ExbjVpN0toQUQ3YjBnZTlSOWM2R1g4cFVSVndhU3cyS0VTblZDdlNQNWhzTXlK
      NWM0cmVpMHBsK3JxNjJZZ1poemxyblR4cVhibll1VzAxV010UUlnd2pUU2xDd2k3
      TnJBSU5vNnA0UDE0RVdUUVJCd2ZDUUIxdkgyaG0vVVdQZnZWaWl3M1VLZzBWL2N6
      aExWTEtqVUpmeTFaWE1aRnk3VWZ6MUpSUk1Bc1ZndTJrLzl4Uy9RRDc3b3pxTUgr
      RmVOU3JMNzBTSFVhaGtFK2tNZmlqN05ubmcvdXZFaXpKa3libjF6ZWRoNDJhSytG
      T3FYdjE4K3h5dWUrS3NURFY3eVJacXplek1wcW9xWXFaQUVmeVFRPT0pCjE1MjMx
      ZTFhNGExNDA0NTJiMTVkYmI3ZDg0MDZmYWJjKGl6MHVLTlhhb0M4VHRCU05wQkc5
      Zk5ISUp5S0ZpY0I4aXJTYmo3c05NTkEvQW1oZW1DRk5tOEtFbHRXOW5nSDRIc05Y
      Z2FKTGw2bXE0c3lORFVIQW1PWHQ5dXpqTmRrQjNGSjkxemVvRW9RN2xMWEYvSE5u
      b3ZOVXdkMmNFOHczelFHbDNRT0FCWVFKU2JnVTh6ZHM4YXJyTUxJM09XYTFvRzdn
      QXJIanBxZ3Z4ZU9CeHIva0xUNDhMaEs5dHpVR01KaEtzUGtSdExkNFM1bnlWeFI5
      TkQ1Uk1sN3NpbjdrcFhjYjhiZEEyL1ZTS1VSRHM4L3ZvdVQ4Ukd0ZW1xNVpYMHJz
      Yno0ZHd1YVNEaHBxSzI0N0pFNE5aTmdUR2I5VGJURndvaGNtVmdlcENiblVjRE9j
      TGhvUFBBelppeWY0VVNoUGN1TXdCODgwOVN3OUpkSFppYUpCUVAvSWg0Zk1lU2lz
      blhHcFZnazdSNTlBeXpodUpSdHJ5eE01WjRmcGRGelkzR3N2bTEvTGtaMzNIVGdC
      LzZ5V3VIcGZHdU03R2dnTHJaUmJzeGhLU2IxZmFUNXN1dm1Wb2FpUVNFOFpoeHEz
      ZUsrN3pwL2psNEpCVlRRUUowZU4va0ZnNW9HOStiV3dQQ2FXTlJ1UURkWFR3a0FD
      c0VlL3ZURnV1eDRkaklTVVFGRHR3dXByUXJySWJXZmZOWkM3V3hlc212RG0wMWh2
      Z1Fianp2c0tVTmkrWTZwZGJKWHUxNmZwQVBobkhhOGNVbmlXSUp5cXBkNmUyMGwv
      NDhHNytSMm9PbXRJN3ZNMWVzS1FpSjZ0U1Zoc1UyUWhLNG1kQms3ZG5Oa0RhaXVp
      eWJVRFlZaDQ2NG8yOTVCV0JmUVNXRmc4UVd1TDlvOWluRzR5cHpnPSk=
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 15231e1a4a140452b15dbb7d8406fabc
  service_keys: []
  shared_key: cc24e454e4b8a954bf3a9037af3058fb
