data:
  project_id: demo-project-2
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      Y2MyNGU0NTRlNGI4YTk1NGJmM2E5MDM3YWYzMDU4ZmIoeEZWSXMzVGV4WkhCaXNx
      RXJnK0NVN0plTEhZV1VvN3ZEd0RYQTFBZEdlKzhHM1BhUXd2UkRvQlhvd01RSHU2
      NlpNVVZuYXpLMHFFZzRkVkZNYVZ3UEQrUEFNTUpYT0FYNXlEYjFlc3hMTTBXNk0z
      RC9YYTdNcy9YR1dQeTNid0trRVNXVVBoWEt6ZHFwMDA5UnErbjRaL2krTFI3c1Nz
      bEJqRERHS2dlQk1rZTlNemRadmZtczNvQjNJUWp5ZW4zWHRtRmJpeUlWN3VLelg0
      cWNCa1FjeDJPOEdDUS90VDBQRTZnaHBpVkkwWG5BcFcvTnNKTHRhbEFRajZLVU80
      dGJiQmcvTGxuZkZJU01vMlFKUFY4OEpFZlduNk5Ba0E0d1NCTHV2c2VMU2l1c0s5
      cHNvdjBsaE0yNkF5cXVaTnhlRGFYc2VxL0xtYkN6RENYNGtWNUl3PT0pCjBkZGM4
      NDJhMjI4YTY1OWU1NDU5ZGEwNWZkMzMwZDM2KGtvMDdMMlNDRGlHSzlPRnFtVEcr
      T3hpVlMwWkpYNHNhSDFBOUcvWGNhTHloVzNtdlFZd1RhTUxKRXhHMUVkTVZ3TXgy
      NVJ5L1NGbm16VGJTbWRPSEdGaFA0OFpTVlVlZXlTMXM3MHRIdjExSlUyVmpqTm5m
      VnZFdHZMUUdBcXlJV1g2cnhTclRvS3RlNms2aXg1RGZtZGxhQUJITDZTQzNPa053
      dUJ5Sm1OcEdTWksrTTEzWWhsdm5iejNRazY4cG9aTmVXd1hZZDI0RHhYb1NmZmRX
      bFZPSE80QjZhd0pKS3gxelgzbWJ4MTlyU2FZNVhsWUJGUGJEalE2SGR0dkRuTUJJ
      N1BZQWQ2RG9DZmxwYU4rZUY4SmxhdkxIbTlxRzltSHZxM1JrcXhOL3VNTmtjSUxT
      c3VZaE5lUVI4OVhxMnlmdElKblRwQ1Z5Sy9WUW9XaXd1bW9lR1Fkb29mOTBPSDJw
      Y1FFMlBNT1NDTE9ZcDlZdTZNZ1QwNUkyVlM2Zktmbm1neEpna0xBUkZ2VEovUmts
      MFhRb1V2WGJacGJLb3JsK2IwclBwNEVaYUQ0RkNodklsazhQTld5OVg5WmJ2MlpE
      S0NrMU8wSEJNZmlvaU00NFlWejQzNmcyR2c4ZFUwUklQWVdiT1FpYjJJZEYzSVlV
      bHU3b1JoL2hjTmxkZXRzUThtMmNkVm5TdkZydWc0VXdSRDNOTEFlSnBSY25uYm5y
      OUVMUDk0b2JpUWVJY0s5Vm01UXBpYjJnNWQzTzMrNnZSd2F6OEFScUMwTXV2VkFP
      eG1LaVpEb3F1STU4UndFcWNraWlPLzFWRHVFdGpJMFlpQWFWcXVFMUVwNW5laG1V
      YlNFZDM4SmhMb2lDbjlWN3hrV2x1WW1VN3FlN0dzS2NiUnRaZE9FPSkKMTUyMzFl
      MWE0YTE0MDQ1MmIxNWRiYjdkODQwNmZhYmMoY3lPNlRkeUt6eUFEWFJKZEUyYTBw
      eThKKytBdXNueEJ3eE1lWWg5RlRzYUhpN0FWTUpnTSs0V01WUm9rQXh1N3h4NHVT
      VTM4WnB1UmJCSCtUZW5GVWc2amVobGk4TVlEeDRpYkFGcjRDdnE4RGJiOTRQZFd6
      UVNWemVQU3h2dXNSdkxjZ0hZQ1hOc0Y0K2hFYUlNYjZlZnpWYWIyUllnYjFvSHZo
      VUZYREEwRjBuczBnNlhuN3RXTE9rTFpwSjIyRk9LRHQ1MHkzYkM0R0VFcWQ5TUsx
      ODA2b0Y3dWxXU3RnVVhLeldQZk0rd2pQTDVlbnNLRjBMSGx0WFdoMDN0c0ppazZm
      U0ZXN21IcEFSSzJONXF1ZzBEVk94OTBnZmk4UmlqdDdKcG9keW41TWJ6YTRwRXlp
      dktsc2JDa29IODB1UlFrd3cwcldIUzIwQWkrdCt6T25BR0F0RVhCOG9UMTltTjRB
      aVBCMGdMQXY3VE5tb1gwMzNVaHZ5Skk3czZhRGp4VGs5T0o4aDh1VEZ0NjYzbnJr
      a3BBSitUeitla2xwSzROYjZ3ek1ZVTFOanQ3RXZ4eHNOQVhJMXF4TDV1VFJwazFY
      czJjNUFIMkpVVERxOUFrY3NEd3IyTDU4WGFDMnJMUWI2NGx5eGRUNWE3UGVtYWcy
      YVNqTVFTOFJ0N1NMaTA3WjkvdDJnWHZoTktGTlhaTHNhZ00yTW9kWGllZmVzQmJV
      dnNsUnBBQ0VTSXE5WXM0aVRqV0NhOU5KUlFCZnk1OGlsZ0s2RUJCSjR3VkI3SUE0
      VHM3WWFnQnp4RGo2UUQ3QkZhSURCb2c4S2o1M3NiWXZZbnU0bllVYkdrUDRBV3pP
      M2RWOXhWaWdDUUJISWU4SzQ5NDdPblVOZjZldS83ZWRaVnh0WE09KQ==
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 0ddc842a228a659e5459da05fd330d36
  - 15231e1a4a140452b15dbb7d8406fabc
  service_keys: []
  shared_key: cc24e454e4b8a954bf3a9037af3058fb
