data:
  project_id: demo-project
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      MzRhMzgwMjdiMTRmNmJhYzE1NTVmMzVjNDc1NmJiOTgoZGR0OVZIRXBmTE9KRTVW
      Sm1OWDczKzZ4ejI0a2xOYzlLZTZZRkFJTVBENmtZUTd5ZDZIV1hKRXQwcytFNGJV
      bnNjYlF6UUFLeHU4UDc4bnJ2a1YxNUdqTWRjc0lXSCsvRElmV21BV3pxbm1OZFZ4
      YkpmWlJtcHJzWHVrWTJGWk1IazhZcFBWdFc2aERhK1JtcDN1eWg0Nm9DM0NSY2RM
      UCtVYzU0YUhFNlN2TVVjaDc0UWo5TkpFbG1RYStSV3R0WDUvRlUxT25id2d6SzEy
      MHRzaHdxYzkwOFIrdXNCTzZBYTRZcGNEZ3FGdFVCMW5QSUpyY3EzOTE4bGVRQ0I3
      enY2bDZpV0NudkltWTA4WkNnSlRUMzUyOTc1azVMd2dIdE1LdVYwRE5zNUw3V3dV
      V0FJRmVUWkxRTERPOHVucDZ6ZWYrelZZcWY3dTRONDY3ZkJZWUR3PT0pCjg4YzIw
      ODY5ZjkyZjJhZGRlMjNiZTM5NjA3ODI5MTFhKEFrQi83ZmJtY0xyN0wzTG1YUmNq
      dUJZQTB4SGM1RzF0R2Z1QmlMTjRsdEdjUVJjcDRZd0plS0NtbDhaOEVIM09ZUk42
      OGUxYjlWVTRjcXc4bGVTeXZsZGVpQ2gydGNNWjZLUU4vVlpRR3M4bGlERjQ3d1pP
      SlpXQ0c2ZU1PYUt2QXlSUTNzSm41U0xhVEg0UHU3Skp3MEZoVFkwdEZnQ2dUb2Vi
      bWlFcmIrSGtWMGJtZ2lxQ3Z6QjYySU1NSitZemRKM3JUMC83M2hrd0VlRFRVb0VF
      dHpqdGtCT2FzMUt0QXBlUmRiYkhnMEtXcW9ydlQ2RkxRaFVpcFJZYjNrVTFEN3hi
      cTlyMk1kS0tzWnJBdDJmaXNDNkE4NnNNb0lzMmgxSy8xT2wyQktDdjZzQTVWTFIz
      Ykw0Zm1lcU9UcUhUWXFQaFZqcXRpZWJPZlVadmI2RW92VWw2UlRCbnBSUjg4bFhn
      b2VmUDk5ZFlaMTJQVHFyUXlyNkYxQ1Bwb0JxMm9BY2U2dUpKMUhHM1hpdTlaeHBQ
      MVFxckJDYzkvRnlYVUU5UkZjcXYzZFJtNUdSQ1c2ZVpSSERjSVVkS29SMGJheFJX
      aDBTdFptbWVEOEg5RGdWOHNaYzNGMDNSWnBaQVB0RFVZa1k4b05lY0JRelU3bDdP
      T2did2Zoc0dZMTBuUzI3cTE3STVSTEQyN0EzSjBRak9aMXpqbWlVeldHdUJ0aXhH
      RHc3ZURrUkhWd1QxN0VCQk96bzUwRnFFWjU2ZjZiQSs3NmZxdUViK0s0cU04MGZQ
      eUc0WFFjdGNQd1FyOU5QUjFheGhkZ0ZNSnBBS0hNenNPMEtwNUNaV01scStKZVJr
      Y2JETEhpcFRkZDN1bUp0NEZLZXQxZ2k2c1VXQkxrZ0RGYXdiQ3Y0PSk=
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 88c20869f92f2adde23be3960782911a
  service_keys: []
  shared_key: 34a38027b14f6bac1555f35c4756bb98
