data:
  project_id: demo-project
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      YmU4NDA1MThjM2Q0N2M0MGM0ZTAzOTlmZjBmNzM2MmUoWHJheXJGWU9xS1ZUNW9h
      YU50T0Qrc21yQ29zaVp0TXJHeDl4dm81RSs2dzFtK1dHUC9aaVh1Q04zTVdIZVR6
      TEtkY0xwb2crbG1XcEhQVjNDU1U3NGR0L3FFY0dzQTVoK3U1d1poL3dONzQ4Y0JT
      eVpvOXpHQXdLS3JqMlpnWlV0Z1VoWWZ0c0FFcVdUR2hXdW9XS2ppTWZrczZWaWow
      VG1VdS9EelFQWWF0RFVkeGZxVnhyQjFhT00rVjVPajRxeC8rMVFQaFdrY0I2aUxD
      M1VsSDR3VXhuaTdHV1Q2WmhPcjROajFpQ1NNQ2ZoK3FFWVVzVjR4L3c5cDdqRVJr
      SGYzZGdacTRrdXM2UCtSTE0wZmYwN2VURzVZSnJhQkp3aTBaVXlrU0NDcUgraENF
      M0F0VmNFYlg5YVNlaVhFcmtlZ2J5MGhMZjlNVEtmR3MwZ2I4Tzl3PT0pCmNhMGNi
      ZjMyOTBkNzM4NmU3OGE0ZmI3NDBmYjE1MDZiKFlXOCs5S3Z4UVJxOWZuYTlWR0c4
      cEkxc1BucjluQkdLUkxhb0RhVmlvRFlObnYzbllFT0tINE82bFR2V3IyUDkya2hu
      TCtsSSttbU0yd0VKbEJCY2RuVEhjSzRtVmpXQ3BRQ3hpUDg2bkhlbG04VHlyUW8v
      L3BPNzYxWXhOdTZJYkI3ZXhwRDJQcTlwMnd1YVBLN3ZUY1Y4REdTKy9FUUtOdllG
      Q3hVYlFFMVVLM3U3WjVDZk1pbUFiNlprQmVKSmllWWcxQ0RUQk1Tb0tEeXFhZ3hZ
      RkRoeHpJb2laSldWeklrTlNES0QvQWp0Uzl0eVU2ZExQMUJaTmxtRkl4Y2lGWjZj
      TWtNYVYrMysrd2hHMXhRMjlodlpBNm15NVNvRVExaVUzVG5nSFpyUXVqWGdiR1Rv
      M21EY05hVEtSUWNmYjVXMy94MU03V09WcDM1bjA5N0N3MTQzTkQ4THlrUEtTQ1lI
      Qm1lZ2RZMjBRQ3QvcmJTZVlwOXJoSHRpeVp1Sm9QVk84THFmZ3dCZVMvWXNPQ1V3
      WlNVQlJwcmZrdkxSWGtuUGwzQmpadEJYR2dmb05scVRqbThKZVRIRmsvTFpnZS9P
      bGcxK3RydDdoaHE5aExld3U2aDJFZ2FrM1NjYkR2cFNhU2JYQ1cycDNMYzNnMG42
      UlVTMWM4MFREbkJ1aFZKUjhncm1HSXdnSHo1bnpSL2NLR0RxaWlRWlJaMWlzREVp
      clpaNlhMcFVob2p1Sm1qa1NBV1YvMDAvOEYrekEvdWVtSXRBVTBYQXRpRlBwL0Z2
      ZDR0QnNTTGxiMEdRbHFGMWxZK0ptR2VXaGxhbkZhZVR6bGxNSlZmekxIb1A5b3c4
      b1dndjl1andmd0wvRU84N3RtOUF3K0pIQ2lvMlNLQU8vbnRtREU0PSkKNGU1NzU1
      ZjQxN2QzOWE1YjZhZDg4OGI2MzJiODU0NzAoZkJEUi9mQThpMWRMSC9jcm5lekRU
      OStRN084d2UvTVcyRFFqb1FNVElZL1ZoV3U2Z0J6Z3IvdXdncXdaTVpraEJxZFE2
      YnhmTUE4ZXo2L2lmMmJ1Z2JWN28wcmhOWU9zdUpvbVVLbmVLaDcyWWtSNk1XSDkv
      TzE4NlloY2N4WmxCMVJ4alplQVpueThFR3h0NWErb0gydlJrVGNRTFJpWkFVYXhP
      ODFJV3VPZGF4ZHphSFhreDBqSUVXK3FDOUNHTFRiU3FXSmRPQ2RpOEtvZWFRWGZ3
      TXp6Sm8zSlFWY2M2QmpqL3dnMDJkOVh3VkFzTzZTUThhb05RZXBoei83M3ZnM3dK
      TmdITnB3ZFNPcHRZeTQ5OExlZkg2aVQzTGwrRXVJOVZsWWgwenBmMFdNa3o0cFJt
      cUZBOG1lRW1OU3dKODRSak5vb3V1YU5vNkx5VFVZQkNpdjZDQ1pIcENyaEJJK0J4
      c245dWd1ZmxEVGJ0NGM5Mi9SMmxxVEtUWlBnaUJyenVydTdhdFJ2RjIwMmJmWmJP
      NndyMnJBZ2pVWDZEZHovSmZiV1hDeGlxOVl4bDN6d3hCazJPdjhIUWhOQkM3K2NU
      RHpaalp6U1RQZzFoZ3B4MExQNFdhYWZrWVdHRHArVEJtQnRMdHJjaHVQYTROaG9F
      R2llT1cvbjViNnRlVlNqQXdYMVpYM0tlelV2TkxPd2N4L081S0M1dkFnNGNoVjZu
      Szl0bHc5SXZBZitVcWZqaldHN1Iydjd4UnpSd3FlV3V6OHZqMm1kNFVzVjBQaWFY
      d2krYVJ4ZkoxU1YyNzJ1YmVNQTRtdUpmR2NQOW9RM1czSXVtVWY1dS9zQ3llTGkz
      RWx4ZHo0TUl0ZWxGQ2FJemhyVm5SYjhMVk5ZV3NIdDI0ZkF0eGc9KQ==
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - ca0cbf3290d7386e78a4fb740fb1506b
  - 4e5755f417d39a5b6ad888b632b85470
  service_keys: []
  shared_key: be840518c3d47c40c4e0399ff0f7362e
