data:
  project_id: demo-project
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      MzRhMzgwMjdiMTRmNmJhYzE1NTVmMzVjNDc1NmJiOTgoVlcvbCtBeUo5RU5qUEc2
      cjhwNlpHVjh5bFZlYnVSQU1KSTQwU01vTU12NHA4UHR1cUJPTThQNmM0eldnTVBX
      bXRnbDF4U0NZQVhkWEthQ05RUWtwZFhBTmVkVjhITzNVbEFKRmJYZVFuNTd0eGVC
      SUlLNVA3R3lubEtxVDNyUFYvSWlFV3hGRi93TjI1Rlp0TDBqTCtzMXBWRnlLeXE0
      MlJIQjBab0tQSFQ0SGdEOWcwQXVncmEzWWx0SGFoL0wzbE1NTEl1UWdVUjVqbURS
      UmlneWRXcDM2YjdiNjN3cFhVZXkySW5MM3FQcFFuNFVmZ09xd0N3K1cwREt6MFRH
      ajBqOHFPbHpFblBZOURtdWt6YXZHNGN1SExNLzZXcW4xM1JlTGNOZ3Z3K0N1bkli
      VGZzMzRLaUNGWkVCaUEwakUzTGdXMTFnalFvWFFDV2thWlN5UElnPT0pCjg4YzIw
      ODY5ZjkyZjJhZGRlMjNiZTM5NjA3ODI5MTFhKFNJc3ZpQ2I0Yy9zc2tXNHpkb2x2
      ZmlOTTl6TTRpZldMZ0NYcE8wbWhBYlVXMlFBajRaMSt0ODZhblh0dGlodGxXQWpL
      cjNWRG9kd0FtblEyVGJNdEFGSlRMcmZVbXlwbEtyUFBIVzg3TjFUWHFTU1owYjhJ
      azRPUXhJTGdvRDJhaGVNd01LaE5DalBnREt4Ty9aS2hXQWpVZVUyTjBrZVI5N3B1
      Qk1ZOWlzMlEyaER5UXhraTh5TjJadk9FYjlWZkdRazdVOGVrU3Fsc01Ubi9CbTZl
      eU83NmppN3gydGd0dXo5cDB5Z05KV1B0SjdabWZ1KzE3VG1YS3ZYNGJaSUJGR2o3
      aVNPT0UvWURKRUliT1hHTTc2SUVieUdvZCtMRHNySmNXTkI3cE1KN29zVEtYeGhy
      QlhOTWpzcjFubEhjWTRDd2p2ck1CV1QrcW1YZGk5SHprRzRRTEdkRnU0QzhGc2Ri
      ZW9oSllET3F5azZvY3NneUFISEIzRDRVMFN2SnBKbWUyWVRvMUhLWlNwazdMV29O
      VktwR0VXQ3JFbjB6UG90OWZWNXJjS00veVRvZHU4Y3pVOEJ5RE5ZOTI5Ri9CN0Fa
      UjNqSHRPWWp6T0NZcjhxRFFjMHRGcnNMWkRCek51NGdoWlR4QVJpQlRCZ0pya0wv
      WHlqMGFNRHU2NlR5d0tBdjIzSWpkVjdQVmRLaHplY0dld0wxeXFVT0IwQWNKNVpi
      cC8yUk5GZTdrS0dRdVowaFpZeGVISUxjeU5Bc2lLU2VReHlHRG5jcjJBaHdMZHFM
      eGhaRTVoV0JSRXhOTE9zL2VWL2VRSGlkUEtLYW1KTlM1M1FKbWJ5Z0hzQUZSYlM4
      TWNSZmMwUUhQaXUzNmNPd2hyVVNZb2VTUnBrUC9xV2xMQ1hvUkNzPSkKNmI4NjBk
      ZjdjY2UyYjMzYmY3YTM1MWU0ZjAxNjQyYTEoQ3JzM1AzWkNiN3AvMDB1U2VLZkc1
      d1JUTjhsdlhyZW5BeXVjWVIwcUYvVWxsUm1QM0lxVjFtRVNPZ0d0RldraWNETHV3
      S01mTHNsdFhjai9FdDVLWkNSeHNnVEVaMUZ5VG1xMXlkZ1ZQaGJiR1VwMkxXdG9B
      SWVIRUlQQXBOclNvVlQ4b3pucmt6Zys3NTdOa3ROMTRuMGRqV3ZRak1BbFp2NEFT
      RUJEZzR0UDRHY1hnbG1BRko2RVBQK2lwb2s5YlJhM3V1Yjg0UjdJVzFMdXRlM1Bk
      SzlOZnZJcUxrUDFpUzVDMndqZzJuN3ZodmVwQzExK0pmenpZZFA4UkhTTzUvLzdi
      bnRFVGxqT1IrSmJVQ3lSeUZ1bVhZUmZiR1FIRks1ZjlxbmVKUFp6ZUZRV1FJelhK
      S3JXdElBa0QrUCtlNnVzZHlwQitlMWhNY2F4dkd5RkFPeGgxQ04xd2Zvb1A0Yms3
      cWJtRFJYVVo2WWtKSnRlRktZVnFCUzlHdElmcDlKRjhTdDJjcXlzRmgxczB2dXdw
      cWl1TEQwUzBZaWxZaEdONks5ZFRjcTlyYU5VT1dLMHZlTDNhQUdNMjRtQmMwYzNY
      dHNOL3Q2dk43ZFh4Q3hWNjZJM0pPRU12dllLQmhpU3JncWJCT1BuUC9PdFNJbEpU
      VnlaSHc1TkVOT05sK3RabVcxa1U5TGUxd1IyenBRNFdHZ01SUDRHMWRpd296Ukt2
      M3FORUJrajY0akRTUjBsRWVueHh1Ykh1M2hxRzIrb3M0YVVOUEJTM0lxbWt5dVBh
      Y0JTeS9FTXpndDA1MkJRWnlrd1RVdFpPSGthM1EvVyt2RWVTY2VsUjdHekgvcGtm
      enhyb3M2R3NMb2lXRU56cjFFNUJFMlEzNUp4dkJCeXdFVEw2ZnM9KQ==
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 88c20869f92f2adde23be3960782911a
  - 6b860df7cce2b33bf7a351e4f01642a1
  service_keys: []
  shared_key: 34a38027b14f6bac1555f35c4756bb98
