data:
  project_id: demo-project
  variables:
    MONGODB_CONNSTR: |
      -----BEGIN PADL ENCRYPTED SECRET-----
      MGYwZGMzZmE1NDU1NzliY2M3ZGY3OThlNWJjMjViNDMoYmJSVktaNzROVHlGV1lx
      TVhJeGJXczFKMWJwbjhHaEhBUFRyTmcxUE8yVW9POXdUcjNlMjlHVGFJZ0ZWNk0x
      SnhMV2Q0NEc5QjlaZFcyNVlCVFNncHY3L3haMjlIemNCTUMzNStnMTRDNzBtOWRM
      dUR0MDdEblVsSnl3bWFIZDNNMVFYMUcwNVNWL0h2K2h4bWNzdXNTSmR0QVFkcGtz
      WUozTzRkYnBsSnh4N0VxNUdXbzc3eHVOVmU5aXZnUmlYZkNBbExueHZndkdrTDBB
      RlEwbjcrOXREZjFGbUtCM0lMNEVhRmozZDBRNFRZSWthdGs3T2sxdW43S0I5SVlj
      ZE85M3BjeHpGVnBHZktQUlJJYUFpVDRheWtkUFh0NUVZU09RU1p1VTc2Q2VhWTE1
      N3BEVmgvM0VmelNtdE9GbkNsWjI3T2hMVlhNTDRKaDhPelhPK2pRPT0pCjYwOGY4
      M2I2MWYxNmUzY2YwZjhiMWFmOWI3OTUyNmEwKEhGSExuWkQwcTRBQ2dIU0s0TVpH
      SkVmQk1rQ0tHSUJGeHJUVnQ3bkx0TEVjT1FFYnRkSWtRdExiRnh5L0N4SE5aVUpr
      bTN6dVBpcnkwdEM1N0ZTaEdZb0h3Z1BmWG9xT3Z3WTdTSHVETlZ3K2tBSVlUZHBI
      UTVkOS9NejFWbWpLaEdPZGlTNktnWHVsOHpwVWg1Q0d5NnMvNEtuaHArRHBTVGZG
      QnRTb3prTWhTOFRDRUUvT1BXQTh4UDJVaHhsSUhlR25Gc05rQXp5dnVqM3V1dk8v
      NWYvOEtTQ2RMTUxSVWJiWjRoT1ZMS3ZNQmkya0Q1V284T3g5Z2lDd3IzS3c1bHQ0
      bkVBMEJEdEl3aEk0V0FVN0wrUE5FZHJhSjZrY1lxQVJoUDI2a2NOdHZNa2RmU3Z1
      NjRuVy93dzJ5c3h4NVhVTCtVWklCRGFhdkk4ZUxyUVl6a0ljdVZJbHJlSHJ1U0pW
      a0pzZk9MUGlhVXIrcGtHMTU2T3NYUmV6UzlNNlFHT0krc3pOSXNzTzRzT2hscXRl
      YklmNkxnRm82L0RFWU1FRGFERTRZYVB4aEVabTN4QTJ0U0syUStMK1NSTFNuajV6
      VllCL0xHOTB3UnFlM1hFSnhwek5pNStmZWFPcFBER28zQ2d2a3hKRnN6STJ0czBV
      OTZDS1lDQXFNTlNrbFpkRWFOdU5KV3M5QjdBajlBWnJCN2VIVEtSRCtPdktwVU5Y
      M3JIU2dyMXh4blpqelhTZzlhVkhJNUJPT0luWjd1YlkrTkVFMTd0SVBxc2E0SjFp
      ZWdmRGp1TlVnMGV1UXIwQVEyeWZIWExMUmlaQXlWWlZHZnhkUTNkY1NkRDhUM1R0
      Vjh6bVEyZmhwSXNGSHpqam45MHlrSVJIdUlQUnZPQXRNMHVwbmdNPSkKMzZjYTY1
      N2E1ODQ2MmRkZTk1NTNhZmExOTE4Y2NjMTcoY3RKZ09NbFhxL0JCNlFuYWl3ejI2
      V1VkM3EvK1FBem4xWklmMnZETENUdFFGbm5Ba1hscDVESFhmY3U1b0lCYzVnTVli
      c0xFMjNuNmFkR0c1NzhnQlFZcWE5Z2R0ZXAzbXJrN1JPNXZQZ3h3ZGZmTFhYOFdQ
      a0dweVQ0MXdvbVhVc2huUzZBbjZqaVlnQjZYc1BmYTh1YUpTWGxDS044MkRxclNr
      K09tVHdxVjBtcUVnNlQvK1FBR3RWcXJTSHNCTisyV2FGTXZPbE92OWRJd1R0b0Zr
      NjVWaFJPOWVjTU5ZRFpNLzdsT0F5c3FxbUU5dHgzbndEOXhZYkErdTg0MXFvZHdi
      SWp5RldsOGEyTFZsYlNHSGtIK043dkcxc1RlT3RFMzZLNjRzNXhBUFVmOWJRckI5
      ZDVWMkErNDhQdExEcE9JL0RDVW1mVFl6K2I3WjhEaFh1ekx6cERGdjZNNnlqdm1T
      VCtpQUM3SlB6MVEwTHFoUlRtMjlGdEs4NjdnbWlib2ljQzg4czRZcEZyZXNhVnQy
      OE9Dby8xY1hXMjE5dk1YUGRvZmZxNkI4UWFHUDBjeTQ4T3lCVGNFZEFIOFBWVy9k
      NnpsQVRwaDNZWk1icGpPdDBVcnB5Z2IxdHhGamphOE9UWUMzbnpOVlhiQ2EydytS
      YkljdUgvNHl5NDVtZW83NFdTbUl3dDVSOFFUOUE5clF0NkNEaGtneXk5TU9iM2dK
      NWxKd013dkt4MXppOVFWUmYwQm9hdURocVJCa2xPczJmb29DOTNYUGpEYUE3VEhi
      ejNMcXU2SDBCZlZrNml0b0ZzQitEZzdhNTVKb1VQL1YyL1E1bEFvd1JYdVR1RUFS
      RUhmUkUyTTAwRGlYQzFyb3dYckRnZml0UXArS3lvbGUvREZDbXM9KQ==
      -----END PADL ENCRYPTED SECRET-----
  user_keys:
  - 608f83b61f16e3cf0f8b1af9b79526a0
  - 36ca657a58462dde9553afa1918ccc17
  service_keys: []
  shared_key: 0f0dc3fa545579bcc7df798e5bc25b43
